# -*- coding: utf-8 -*-
"""goroku.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y_Ipdtn_cnwvd4Kt3uStwlS5WwXv1iC0
"""

import streamlit as st
import random

# 語録リスト（適宜追加可能）
net_memes = [
    "やっぱつれぇわ…",
    "でもよ、俺は止まんねぇからよ…",
    "なんだァ？てめェ…",
    "そうはならんやろ",
    "はい論破ァ！",
    "異議あり！",
    "てめぇこの野郎…ぶっ殺してやる！",
    "俺の怒りが有頂天！",
    "にゃんぱすー",
    "お前のような勘のいいガキは嫌いだよ",
    "全てはシュタインズ・ゲートの選択だ",
    "見てろよ見てろよ～",
    "ちょっと何言ってるかわかんないっすね",
    "いや、まて、落ち着け、考えろ",
    "お前…消えるのか？",
    "おい、デュエルしろよ",
    "これもうわかんねぇな",
    "あっ…そっかぁ…",
    "あぁ^～心がぴょんぴょんするんじゃぁ^～",
    "インターネット老人会",
    "草",
    "大変なことやと思うよ",
    "えっちなことしたいだけでしょ",
    "お兄ちゃんどいて！そいつ殺せない！",
    "ぬわああん疲れたもおおおん",
]

# アプリタイトル
st.title("🌐 ネットミーム語録ジェネレーター")

st.write("ボタンを押して懐かしの・または今でも使えるネット語録をゲットしよう！")

# ボタン
if st.button("語録ください"):
    selected_quote = random.choice(net_memes)
    st.code(selected_quote)