# -*- coding: utf-8 -*-
"""iiwake.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h5aE8rbZCv_lflSjcAwiL4ppJoLsvods
"""

# 🔧 ライブラリをインストール（最初だけ少し時間かかる）
!pip install openai streamlit pyngrok --quiet

# 🔐 OpenAI APIキーを入力（※自分のキーを入力）
import os
os.environ["OPENAI_API_KEY"] = input("🔑 OpenAI APIキーを入力してください: ")

# 💻 Streamlitアプリのコードを書く
app_code = '''
import streamlit as st
import openai
import os

openai.api_key = os.getenv("OPENAI_API_KEY")

st.title("🧠 GPT言い訳ジェネレーター")
st.write("状況を入力すると、GPTが自然な言い訳を考えます。")

situation = st.text_area("❓ 言い訳したい状況は？")
tone = st.selectbox("🗣️ 文体は？", ["敬語", "タメ口", "どっちでも"])

if st.button("GPTに相談！") and situation.strip():
    with st.spinner("考え中…"):
        prompt = f"""
あなたは“言い訳のプロ”です。次の状況に自然で納得されやすい言い訳を考えてください。

状況: {situation}
希望の文体: {tone}
"""
        response = openai.ChatCompletion.create(
            model="gpt-4",
            messages=[{"role": "user", "content": prompt}],
            temperature=0.9,
            max_tokens=300,
        )
        st.success(response.choices[0].message.content.strip())
'''

# アプリコードを保存
with open("app.py", "w") as f:
    f.write(app_code)

# 🌐 外部アクセス用のURLを作成（ngrok使用）
from pyngrok import ngrok
public_url = ngrok.connect(8501)
print("🔗 このURLをクリックするとアプリが開きます：", public_url)

# 🚀 Streamlitアプリを起動
!streamlit run app.py &> /dev/null &