# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18Qn-Ot8GKGa4xyMUHbd4a62OvV7Be6hO
"""

import streamlit as st

st.title("🏋️‍♀️ BMI（体格指数）計算アプリ")

# 入力
height = st.number_input("身長（cm）", min_value=100.0, max_value=250.0, value=170.0)
weight = st.number_input("体重（kg）", min_value=30.0, max_value=200.0, value=60.0)

if st.button("BMIを計算"):
    # 計算
    bmi = weight / ((height / 100) ** 2)
    st.success(f"あなたのBMIは **{bmi:.2f}** です")

    # 判定
    if bmi < 18.5:
        st.warning("→ 低体重（やせ型）です")
    elif 18.5 <= bmi < 25:
        st.info("→ 普通体重です")
    elif 25 <= bmi < 30:
        st.warning("→ 肥満（1度）です")
    else:
        st.error("→ 肥満（2度以上）です")

# Commented out IPython magic to ensure Python compatibility.
# %pip install streamlit