# -*- coding: utf-8 -*-
"""wake2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h5aE8rbZCv_lflSjcAwiL4ppJoLsvods
"""

# ① 必要なライブラリをインストール
!pip install openai streamlit pyngrok --quiet

# ② OpenAIのAPIキーを入力（OpenAIのサイトから取得したやつ）
import os
os.environ["OPENAI_API_KEY"] = input("🔑 OpenAIのAPIキーを入力してください: ")

# ③ Streamlitアプリの中身（GPT言い訳メーカー）
app_code = '''
import streamlit as st
import openai
import os

openai.api_key = os.getenv("OPENAI_API_KEY")

st.title("🧠 GPT言い訳ジェネレーター")
st.write("状況を入力すると、GPTが自然な言い訳を考えます。")

situation = st.text_area("❓ 言い訳したい状況は？")
tone = st.selectbox("🗣️ 文体は？", ["敬語", "タメ口", "どっちでも"])

if st.button("GPTに相談！") and situation.strip():
    with st.spinner("考え中…"):
        prompt = f"""
あなたは“言い訳のプロ”です。次の状況に自然で納得されやすい言い訳を考えてください。

状況: {situation}
希望の文体: {tone}
"""
        response = openai.ChatCompletion.create(
            model="gpt-4",
            messages=[{"role": "user", "content": prompt}],
            temperature=0.9,
            max_tokens=300,
        )
        st.success(response.choices[0].message.content.strip())
'''

# ④ コードを app.py というファイルに保存
with open("app.py", "w") as f:
    f.write(app_code)

# あなたのngrok authtokenをここに貼り付け
!ngrok config add-authtoken ngrok config add-authtoken 2ykVq3DmiAplWCK0dJTSM0ycZ6n_5z2CX2i7xPKWq1scb4Py4

# ⑤ ngrokというツールを使ってアプリをインターネット公開
from pyngrok import ngrok
public_url = ngrok.connect(8501)
print("🔗 このURLをクリックするとアプリが開きます：", public_url)

# ⑥ streamlitを起動（裏で）
!streamlit run app.py &> /dev/null &